// Atoms - Basic, reusable UI building blocks
export {
  AnimatedBackground,
  type AnimatedBackgroundProps,
  AnimatedLogo,
  type AnimatedLogoProps,
  Button,
  type ButtonProps,
  IconButton,
  type IconButtonProps,
  ActivityIndicator,
  type ActivityIndicatorProps,
  SidebarItem,
  type SidebarItemProps,
  TabItem,
  type TabItemProps,
  type Tab,
  SearchInput,
  type SearchInputProps,
  ActionCard,
  type ActionCardProps,
  InteractiveCard,
  type InteractiveCardProps,
  StatItem,
  type StatItemProps,
  Logo,
  type LogoProps,
  MenuButton,
  type MenuButtonProps,
  type MenuButtonItemProps,
  Toast,
  type ToastProps,
  ToastViewport,
  type ToastViewportProps,
  ResizeHandle,
  type ResizeHandleProps,
  StatusBarItem,
  type StatusBarItemProps,
  Spinner,
  type SpinnerProps,
  OpenInDropdown,
  type OpenInDropdownProps,
  FinderIcon,
  VSCodeIcon,
  CursorIcon,
  XcodeIcon,
  GhosttyIcon,
  ITermIcon,
  TerminalIcon,
  WindsurfIcon,
  APP_ICONS,
  getAppIcon,
  SplitResizeHandle,
} from "./atoms";

// Molecules - Simple combinations of atoms
export {
  SidebarSection,
  type SidebarSectionProps,
  TabBar,
  type TabBarProps,
  RepositorySection,
  type RepositorySectionProps,
  SidebarFooter,
  type SidebarFooterProps,
  ActionCardGroup,
  type ActionCardGroupProps,
  StatsBar,
  type StatsBarProps,
  InputDialog,
  type InputDialogProps,
  ConfirmDialog,
  type ConfirmDialogProps,
  TitleBar,
  type TitleBarProps,
  RepositorySettingsDialog,
  type RepositorySettingsDialogProps,
  ThemeToggle,
  type ThemeToggleProps,
  WorkspaceStatusBar,
  type WorkspaceStatusBarProps,
  CloneDialog,
  type CloneDialogProps,
  FeatureCard,
  type FeatureCardProps,
  FeatureHighlights,
  type FeatureHighlightsProps,
  type Feature,
  SplitPane,
  UpdateTooltip,
  type UpdateTooltipProps,
} from "./molecules";

// Organisms - Complex UI sections
export { Sidebar, type SidebarProps, WelcomeScreen, type WelcomeScreenProps } from "./organisms";
